---
title: "Airline_Delay_Cause"
authors: "Annie Chan ,Halle Davis, Salvador R. Sanchez Castro"
date: '2022-11-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Arriving 2 Hours Early, Staying 3 Hours Late - Time-Series Analysis of Flight Delay**

**Team Number**: 6

**Team Leader/Representative**: Halle Davis

**Full Names of Team Members**: 1. Sanchez Castro Salvador 2. Lai Ieng Chan 3. Halle Davis

------------------------------------------------------------------------

## Initial Load

```{r Libs}
library(visdat)
library(DataExplorer)
library(dplyr)
library(zoo)
library(ggplot2)
library(plotly)
library(htmlwidgets)
library(tidyverse)
library(fpp2)
library(readr)

set.seed(506)
```

```{r Load Data}
Airline_Delays <- read.csv('Airline_Delay_Cause.csv')
```

## EDA

```{r EDA}
# Initial peek into data
glimpse(Airline_Delays)
cat("\n")
cat("\n")
summary(Airline_Delays)
```

```{r Counts}
cat("Number of Carriers: ", length(unique(Airline_Delays$carrier)))
cat("\n")
cat("Number of Airports: ", length(unique(Airline_Delays$airport)))
```

```{r DataExplorer}
DataExplorer::create_report(Airline_Delays)
```

```{r Date Column}
#To year-Date
Airline_Delays$date <- as.yearmon(paste(Airline_Delays$year,
                                        Airline_Delays$month), "%Y %m")
#To Date type
Airline_Delays <- transform(Airline_Delays, date = as.Date(date))
Airline_Delays 
```

## Pre-processing

```{r Selecting Airport and Airline}

airport_table <- table(Airline_Delays$airport)
airport_table <- airport_table[order(airport_table,decreasing = TRUE)]

#Airports with most flights
airport_table
```
```{r Filter for PIT}

Airline_Delays_Pit <- filter(Airline_Delays , airport == "PIT")
Airline_Delays_Pit

carrier_table <- table(Airline_Delays_Pit$carrier)
carrier_table <- carrier_table[order(carrier_table,decreasing = TRUE)]

#Airports with most flights
carrier_table

sum <- summary(Airline_Delays_Pit$date)
sum
```


```{r view time series}
arr_delays_pit.ts <- ts(Airline_Delays_Pit$arr_delay,
                 start = c(2019, 1),
                 end = c(2022, 8),
                 freq = 12)
autoplot(arr_delays_pit.ts,
         series = 'PIT Delays',
         xlab = 'Months',
         ylab = 'Airlport Delays',
         main = 'Delays for Pittsburgh International')

carrier_delays_pit.ts <- ts(Airline_Delays_Pit$carrier_delay,
                 start = c(2019, 1),
                 end = c(2022, 8),
                 freq = 12)
autoplot(carrier_delays_pit.ts,
         series = 'PIT Carrier Delays',
         xlab = 'Months',
         ylab = 'Carrier Delays',
         main = 'Delays for Pittsburgh International')


```


```{r view time series}
fig <- plot_ly(Airline_Delays_Pit,
               type = 'scatter',
               mode = 'lines'
               #line = list(color = '#326ac2')
               )%>%
  add_trace(x = ~date,
            y = ~arr_delay,
            color = ~carrier_name)%>%
  layout(showlegend = T)
  options(warn = -1)

fig <- fig %>%   layout(
         xaxis = list(
           title=list(text='Time',
                      font = list(size = 20),
                      standoff = 25),
           tickangle=-45
           ),
         yaxis = list(
           title=list(text='Airlport Delays',
                      font = list(size = 20),
                      standoff = 25),
           plot_bgcolor='#e5ecf6', width = 900)
           )
fig


saveWidget(fig, "Airline_Delays_Pit.html", selfcontained = F, libdir = "lib")

```

```{r}
# To partition the data using the period until December 1993 as the training period
Airline_Delays_Pit.Valid <- 12
Airline_Delays_Pit.train <- length(arr_delays_pit.ts) - Airline_Delays_Pit.Valid
Airline_Delays_Pit.train.ts <- window(arr_delays_pit.ts, start = c(2019,1), end = c(2019, Airline_Delays_Pit.train))
Airline_Delays_Pit.valid.ts <- window(arr_delays_pit.ts, start = c(2019, Airline_Delays_Pit.train +1), end = c(2019, Airline_Delays_Pit.train + Airline_Delays_Pit.Valid))
```

```{r}
# Use the ets function with the option model = "AAM" to fit Holt-Winter’s 
# exponential smoothing model with additive error, additive trend & multiplicative seasonality
wine.hwin <- ets(Airline_Delays_Pit.train.ts, model = "AAM", alpha = .2, gamma = .05, restrict = FALSE)
wine.hwin
```

